services:
  web:
    image: ${REGION}-docker.pkg.dev/${PROJECT_ID}/arsip-template/app:${GITHUB_SHA}
    container_name: arsip-template
    ports:
      - "3000:3000"
    restart: always
    env_file:
      - .env.production
    deploy:
      resources:
        limits:
          memory: 1024G
    healthcheck:
      test: ["CMD-SHELL", "free | awk '/Mem/ {exit ($3/$2*100 > 80)}'"]
      interval: 1m
      timeout: 10s
      retries: 3
