- name: Deploy to SSH server
        env:
          REGION: ${{ secrets.GCE_REGION }}
          PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
          GITHUB_SHA: ${{ github.sha }}
          GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} '
            cd ${{ secrets.PROJECT_PATH }}

            if [ ! -f docker-compose.yml ]; then
              echo "docker-compose.yml not found in ${{ secrets.PROJECT_PATH }}"
              exit 1
            fi

            export REGION=${{ env.REGION }}
            export PROJECT_ID=${{ env.PROJECT_ID }}
            export GITHUB_SHA=${{ github.sha }}
            export GCP_SA_KEY="${{ secrets.GCP_SA_KEY }}"

            # Update docker-compose.yml to include GCP_SA_KEY
            awk -v key="$GCP_SA_KEY" '
            /GCP_SA_KEY=/ {
              print "      GCP_SA_KEY=" key
              next
            }
            {print}
            ' docker-compose.yml > docker-compose.yml.tmp && mv docker-compose.yml.tmp docker-compose.yml

            docker-compose pull
            docker-compose down
            docker-compose up -d
          '