name: CI/CD Pipeline

on:
  push:
    branches:
      - main

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  GCE_INSTANCE: arsip-template-vm
  GCE_INSTANCE_ZONE: asia-southeast1-c

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v0
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Build and push Docker image
        run: |
          docker build -t gcr.io/$PROJECT_ID/arsip-template:${{ github.sha }} .
          docker push gcr.io/$PROJECT_ID/arsip-template:${{ github.sha }}

      - name: Deploy to VM
        run: |
          gcloud compute ssh --zone $GCE_INSTANCE_ZONE $GCE_INSTANCE --command '
            docker pull gcr.io/${{ env.PROJECT_ID }}/arsip-template:${{ github.sha }}
            docker stop arsip-template || true
            docker rm arsip-template || true
            docker run -d --name arsip-template -p 3000:3000 gcr.io/${{ env.PROJECT_ID }}/arsip-template:${{ github.sha }}
          '
